# Generated by Django 3.1.7 on 2021-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0005_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
