# Generated by Django 3.1.7 on 2021-05-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0006_auto_20210504_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='owner_ID',
            field=models.UUIDField(blank=True, default=None, editable=False),
        ),
    ]
