# Generated by Django 3.1.7 on 2021-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0007_auto_20210419_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='owner_ID',
            field=models.UUIDField(blank=True, default=None, editable=False),
        ),
    ]
