# Generated by Django 3.1.7 on 2021-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0008_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, max_length=255),
        ),
    ]
