# Generated by Django 3.1.7 on 2021-04-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0008_books_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
