# Generated by Django 3.1.7 on 2021-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0009_auto_20210421_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
