# Generated by Django 3.1.7 on 2021-05-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0010_auto_20210506_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
