# Generated by Django 3.1.7 on 2021-05-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0011_auto_20210506_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.UUIDField(default=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
